version: '3.9'
services:
  pigallery2:
    build: .
    container_name: pigallery2
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
      # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend for development
    volumes:
      - /docker/stacks/pigallery2/config:/app/data/config
      - /docker/stacks/pigallery2/db-data:/app/data/db
      - /docker/stacks/pigallery2/images/gallery:/app/data/images:ro
      - /docker/stacks/pigallery2/tmp:/app/data/tmp
    ports:
      - "127.0.0.1:3456:80"
    restart: always
     
networks:
  default:
    external: true
    name: bart